# https://medium.com/@doedotdev/mypy-for-github-action-7da1ebee99e7
name: Mypy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install poetry && poetry install
    - name: mypy
      run: |
        poetry run python3 -m mypy --strict sansio_lsp_client
