# https://medium.com/@doedotdev/mypy-for-github-action-7da1ebee99e7
name: Mypy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        pip install poetry && poetry install
    - name: mypy
      run: |
        poetry run python3 -m mypy --python-version 3.6 --strict sansio_lsp_client
        poetry run python3 -m mypy --python-version 3.7 --strict sansio_lsp_client
        poetry run python3 -m mypy --python-version 3.8 --strict sansio_lsp_client
        poetry run python3 -m mypy --python-version 3.9 --strict sansio_lsp_client
