name: Build & publish to PyPI
on:
  create:
    tags:
      - v*

jobs:
  publish:
    name: Build & publish distribution to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Setup poetry
        run: python -m pip install --user poetry
      - name: Build
        run: python -m poetry build -vvv -n
      - name: Publish!
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python -m poetry publish -vvv -n -u __token__ -p "$API_KEY"
