on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]  # TODO: Python 3.9 support
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        pip install poetry && poetry install
    # TODO: use poetry properly
    - run: |
        poetry install "python-language-server[all]" pytest
    - run: |
        poetry run pytest -v tests.py
